---
title: "Data_Visualization"
author: "Rose Porta and Clara Li"
date: "5/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
# read in data
data <- read.csv("data.csv")

library(tidyverse)
library(broom)
```

# MODEL FITTING

## Model 1: SIMPLE MODEL
```{r}
model_simple <- glm(chronic ~ HRSLEEP + I(HRSLEEP^2) + depfreq_often + depfreq_monthly, data = data, family = binomial)

summary(model_simple)

# significant coefficients: all

# Results for simple model:
# sleep significant at 0.001 level, p-value = 0.000447
# sleep squared significant at 0.001 level, p-value = 2.05e-06
# depfreq_often significant at 0.001 level, p-value < 2e-16
# depfreq_monthly significant at 0.05 level, p-value = 0.011191
```

## Model 2: FULL MODEL
```{r}
# New with transformed sleep, excluding interaction with the original sleep variable
# AIC score: 3297.7

model_full <- glm(chronic ~ HRSLEEP + I(HRSLEEP^2) + depfreq_often + depfreq_monthly + I(I(HRSLEEP^2)*depfreq_often) + I(I(HRSLEEP^2)*depfreq_monthly) + log(AGE) + SEX + BMI + activity_score + income_high + income_middle + race_asian + race_black + race_na, family = binomial, data = data)

summary(model_full)

# significant coefficients: sleep, sleep squared, depfreq_often, all covariates

# Results for full model:
# sleep significant at 0.05 level, p-value = 0.0317
# sleep squared significant at 0.05 level, p-value = 0.0149
# depfreq_often significant at 0.001 level, p-value = 1.40e-05
```

## Model 3: FULL WOMEN
```{r}
# Data 1: only women
data1 <- data %>% 
  filter(SEX == 1)

model_women <- glm(chronic ~ HRSLEEP + I(HRSLEEP^2) + depfreq_often + depfreq_monthly + I(I(HRSLEEP^2)*depfreq_often) + I(I(HRSLEEP^2)*depfreq_monthly) + log(AGE) + BMI + activity_score + income_high + income_middle + race_asian + race_black + race_na, family = binomial, data = data1)

summary(model_women)

# significant coefficients: depfreq_often, all covariates except race_na

# Results for women:
# depfreq_often significant at 0.01 level, p-value = 0.00145
```

## Model 4: FULL MEN
```{r}
# Data 2: only men
data2 <- data %>% 
  filter(SEX == 0)

model_men <- glm(chronic ~ HRSLEEP + I(HRSLEEP^2) + depfreq_often + depfreq_monthly + I(I(HRSLEEP^2)*depfreq_often) + I(I(HRSLEEP^2)*depfreq_monthly) + log(AGE) + BMI + activity_score + income_high + income_middle + race_asian + race_black + race_na, family = binomial, data = data2)

summary(model_men)

# significant coefficients: sleep, sleep squared, depfreq_often, most covariates

# Result for men:
# sleep significant at 0.05 level, p-value = 0.02085
# sleep squared significant at 0.05 level, p-value = 0.01464
# depfreq_often significant at 0.01 level, p-value = 0.00292
```

# Bar chart showing counts for depfreq and diabetes status

```{r}
data2 <- data %>% 
  group_by(chronic) %>% 
  summarise(often_count = sum(depfreq_often),
            monthly_count = sum(depfreq_monthly),
            rarely_count = n() - (often_count + monthly_count)) %>% 
  pivot_longer(names_to = "frequency", values_to = "count", cols = -chronic)

ggplot(data2, aes(x = frequency, y = count, fill = as_factor(chronic))) +
  geom_col(position = "dodge")
```

# Model 1: Simple
```{r}
# code from Logistic Regression visualization practice activity 4/20/20
preds_simple <- augment(x=model_simple, type.predict = "response") %>%
  mutate(lci=`.fitted`-(1.96*`.se.fit`),
         uci=`.fitted`+(1.96*`.se.fit`)) %>%
  rename(prob=`.fitted`)

probs_simple <- preds_simple %>%
  select(prob,lci,uci, depfreq_often, depfreq_monthly, HRSLEEP, chronic)
```

```{r, warning = FALSE, message = FALSE}
# code from Logistic Regression visualization practice activity 4/20/20
probs_simple <- probs_simple %>%
  filter(HRSLEEP %in% c(4, 5, 6, 7, 8, 9, 10)) %>%
  group_by(HRSLEEP, depfreq_often) %>%
  mutate(depfreq_often2 = ifelse(depfreq_often == 1, "Often", "Rarely")) %>% 
  slice(1)

ggplot(probs_simple, aes(y = prob, x = HRSLEEP, color = as.factor(depfreq_often2))) +
      geom_pointrange(aes(ymin = lci, ymax = uci),
                      position = position_dodge(width = 3),
                      size = .75) +
        labs(
          title = "Probability of having Diabetes by Sleep and Depression",
          subtitle = "Model 1: Simple Model",
          y = "Probability of having Diabetes", 
          x = "Hours of Sleep per Night",
          color = "Depression Frequency") +
        theme_bw()
```

# Model 2: Full
```{r}
## ERROR .se.fit does not exists
# code from Logistic Regression visualization practice activity 4/20/20
preds_full <- augment(x=model_full, type.predict = "response") %>%
  mutate(lci=`.fitted`-(1.96*`.se.fit`),
         uci=`.fitted`+(1.96*`.se.fit`)) %>%
  rename(prob=`.fitted`)

probs_full <- preds_full %>%
  select(prob,lci,uci, depfreq_often, depfreq_monthly, HRSLEEP, chronic)
```

```{r, warning = FALSE}
# code from Logistic Regression visualization practice activity 4/20/20
probs_full <- probs_full %>%
  filter(HRSLEEP %in% c(4, 5, 6, 7, 8, 9, 10)) %>%
  group_by(HRSLEEP, depfreq_often) %>%
  mutate(depfreq_often2 = ifelse(depfreq_often == 1, "Often", "Rarely")) %>%
  slice(1)

ggplot(probs_full, aes(y = prob, x = HRSLEEP, color = as.factor(depfreq_often2))) +
      geom_pointrange(aes(ymin = lci, ymax = uci),
                      position = position_dodge(width = 3),
                      size = .75) +
        labs(title = "Probability of having Diabetes by Sleep and Depression",
          subtitle = "Model 2: Full Model",
          y = "Probability of having Diabetes", 
          x = "Hours of Sleep per Night",
          color = "Depression Frequency") +
        theme_bw()
```

# Model 3: Full, Women
```{r}
# code from Logistic Regression visualization practice activity 4/20/20
preds_women <- augment(x=model_women, type.predict = "response") %>%
  mutate(lci=`.fitted`-(1.96*`.se.fit`),
         uci=`.fitted`+(1.96*`.se.fit`)) %>%
  rename(prob=`.fitted`)

probs_women <- preds_women %>%
  select(prob,lci,uci, depfreq_often, depfreq_monthly, HRSLEEP, chronic)

```

```{r, warning = FALSE}
# code from Logistic Regression visualization practice activity 4/20/20
probs_women <- probs_women %>%
  filter(HRSLEEP %in% c(4, 5, 6, 7, 8, 9, 10)) %>%
  group_by(HRSLEEP, depfreq_often) %>%
  mutate(depfreq_often2 = ifelse(depfreq_often == 1, "Often", "Rarely")) %>%
  slice(1)

ggplot(probs_women, aes(y = prob, x = HRSLEEP, color = as.factor(depfreq_often2))) +
      geom_pointrange(aes(ymin = lci, ymax = uci),
                      position = position_dodge(width = 3),
                      size = .75) +
        labs(title = "Probability of having Diabetes by Sleep and Depression",
          subtitle = "Model 3: Full Model, Women",
          y = "Probability of having Diabetes", 
          x = "Hours of Sleep per Night",
          color = "Depression Frequency") +
        theme_bw()
```

# Model 4: Full, Men
```{r}
# code from Logistic Regression visualization practice activity 4/20/20
preds_men <- augment(x=model_men, type.predict = "response") %>%
  mutate(lci=`.fitted`-(1.96*`.se.fit`),
         uci=`.fitted`+(1.96*`.se.fit`)) %>%
  rename(prob=`.fitted`)

probs_men <- preds_men %>%
  select(prob,lci,uci, depfreq_often, depfreq_monthly, HRSLEEP, chronic)
```

```{r, warning = FALSE}
# code from Logistic Regression visualization practice activity 4/20/20
probs_men <- probs_men %>%
  filter(HRSLEEP %in% c(4, 5, 6, 7, 8, 9, 10)) %>%
  group_by(HRSLEEP, depfreq_often) %>%
  mutate(depfreq_often2 = ifelse(depfreq_often == 1, "Often", "Rarely")) %>%
  slice(1)

ggplot(probs_men, aes(y = prob, x = HRSLEEP, color = as.factor(depfreq_often2))) +
      geom_pointrange(aes(ymin = lci, ymax = uci),
                      position = position_dodge(width = 3),
                      size = .75) +
        labs(title = "Probability of having Diabetes by Sleep and Depression",
          subtitle = "Model 4: Full Model, Men",
          y = "Probability of having Diabetes",
          x = "Hours of Sleep per Night",
          color = "Depression Frequency") +
        theme_bw()
```
