---
title: "Exploring a model between sleep and chronic diabetes, with mediation by depression frequency and sex"
author: "Rose Porta and Clara Li"
date: "06/26/2020"
output:
  pdf_document: default
editor_options:
  chunk_output_type: console
---
```{r, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE, error=FALSE}
# knitr settings to control how R chunks work and how the pdf is compiled when knit.
require(knitr)
require(xtable)
options(xtable.floating = FALSE)
options(xtable.timestamp = "")
require(tidyverse)
require(gtools)
require(broom)
opts_chunk$set(
  tidy=TRUE,                     # display code as typed
  size="small",                   # slightly smaller font for code
  tidy.opts=list(width.cutoff=65), # wrap text and long comments
  fig.width=4, fig.height=2           #figure size
)
```

## Abstract



## Background and Significance



## Methods 

### Data



### Variables


  
## Results


  
## Figure 1.1

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```

```{r}
# read in data
data <- read.csv("data.csv")

library(tidyverse)
library(broom)
library(grid)
library(pdp)
library(ggplotify)
library(gridExtra)
```

```{r}

# Fit full logistic model
model_full <- glm(chronic ~ HRSLEEP + depfreq_often + depfreq_monthly + I(HRSLEEP*depfreq_often) + I(HRSLEEP*depfreq_monthly) + log(AGE) + SEX + BMI + activity_score + income_high + income_middle + race_asian + race_black + race_na, family = binomial, data = data)

# Data 1: only women
data1 <- data %>% 
  filter(SEX == 1)

model_women <- glm(chronic ~ HRSLEEP + depfreq_often + depfreq_monthly + I(HRSLEEP*depfreq_often) + I(HRSLEEP*depfreq_monthly) + log(AGE) + SEX + BMI + activity_score + income_high + income_middle + race_asian + race_black + race_na, family = binomial, data = data1)


# Data 2: only men
data2 <- data %>% 
  filter(SEX == 0)

model_men <- glm(chronic ~ HRSLEEP + depfreq_often + depfreq_monthly + I(HRSLEEP*depfreq_often) + I(HRSLEEP*depfreq_monthly) + log(AGE) + SEX + BMI + activity_score + income_high + income_middle + race_asian + race_black + race_na, family = binomial, data = data2)

# Fit model without confounders

model_simple <- glm(chronic ~ HRSLEEP + depfreq_often + depfreq_monthly, data = data, family = binomial)
            
```
  
```{r}
# code from Logistic Regression visualization practice activity 4/20/20
preds_full <- augment(x=model_full, type.predict = "response") %>%
  mutate(lci=`.fitted`-(1.96*`.se.fit`),
         uci=`.fitted`+(1.96*`.se.fit`)) %>%
  rename(prob=`.fitted`)

probs_full<- preds_full %>%
  select(prob,lci,uci, depfreq_often, depfreq_monthly, HRSLEEP, chronic)
```

```{r, warning = FALSE}
# code from Logistic Regression visualizationpractice activity 4/20/20
probs_full <- probs_full %>%
  filter(HRSLEEP %in% c(4, 5, 6, 7, 8, 9, 10)) %>%
  group_by(HRSLEEP, depfreq_often) %>%
  mutate(depfreq_often2 = ifelse(depfreq_often == 1, "Often", "Rarely")) %>%
  slice(1)

p1 <- ggplot(probs_full, aes(y = prob, x = HRSLEEP, color = as.factor(depfreq_often2))) +
      geom_pointrange(aes(ymin = lci, ymax = uci),
                      position = position_dodge(width = 3),
                      size = .75) +
        labs(title = "Probability of having Diabetes by Sleep and Depression",
          subtitle = "Model 1: Full Model",
          y = "Probability of having Diabetes", 
          x = "Hours of Sleep per Night",
          color = "Depression Frequency") +
        theme_bw()
g1 <- as.grob(p1)
```

# Figure 1.2

```{r}
# code from Logistic Regression visualization practice activity 4/20/20
preds_women <- augment(x=model_women, type.predict = "response") %>%
  mutate(lci=`.fitted`-(1.96*`.se.fit`),
         uci=`.fitted`+(1.96*`.se.fit`)) %>%
  rename(prob=`.fitted`)

probs_women <- preds_women %>%
  select(prob,lci,uci, depfreq_often, depfreq_monthly, HRSLEEP, chronic)

```

```{r, warning = FALSE}
# code from Logistic Regression visualizationpractice activity 4/20/20
probs_women <- probs_women %>%
  filter(HRSLEEP %in% c(4, 5, 6, 7, 8, 9, 10)) %>%
  group_by(HRSLEEP, depfreq_often) %>%
  mutate(depfreq_often2 = ifelse(depfreq_often == 1, "Often", "Rarely")) %>%
  slice(1)

p2 <- ggplot(probs_women, aes(y = prob, x = HRSLEEP, color = as.factor(depfreq_often2))) +
      geom_pointrange(aes(ymin = lci, ymax = uci),
                      position = position_dodge(width = 3),
                      size = .75) +
        labs(title = "Probability of having Diabetes by Sleep and Depression",
          subtitle = "Model 2: Women Only",
          y = "Probability of having Diabetes", 
          x = "Hours of Sleep per Night",
          color = "Depression Frequency") +
        theme_bw()
g2 <- as.grob(p2)
```

# Figure 1.3

```{r}
# code from Logistic Regression visualization practice activity 4/20/20
preds_men <- augment(x=model_men, type.predict = "response") %>%
  mutate(lci=`.fitted`-(1.96*`.se.fit`),
         uci=`.fitted`+(1.96*`.se.fit`)) %>%
  rename(prob=`.fitted`)

probs_men <- preds_men %>%
  select(prob,lci,uci, depfreq_often, depfreq_monthly, HRSLEEP, chronic)
```

```{r, warning = FALSE}
# code from Logistic Regression visualizationpractice activity 4/20/20
probs_men <- probs_men %>%
  filter(HRSLEEP %in% c(4, 5, 6, 7, 8, 9, 10)) %>%
  group_by(HRSLEEP, depfreq_often) %>%
  mutate(depfreq_often2 = ifelse(depfreq_often == 1, "Often", "Rarely")) %>%
  slice(1)

p3 <- ggplot(probs_men, aes(y = prob, x = HRSLEEP, color = as.factor(depfreq_often2))) +
      geom_pointrange(aes(ymin = lci, ymax = uci),
                      position = position_dodge(width = 3),
                      size = .75) +
        labs(title = "Probability of having Diabetes by Sleep and Depression",
          subtitle = "Model 3: Men Only",
          y = "Probability of having Diabetes",
          x = "Hours of Sleep per Night",
          color = "Depression Frequency") +
        theme_bw()
g3 <- as.grob(p3)
```

# Figure 1.4

```{r}
# code from Logistic Regression visualization practice activity 4/20/20
preds_simple <- augment(x=model_simple, type.predict = "response") %>%
  mutate(lci=`.fitted`-(1.96*`.se.fit`),
         uci=`.fitted`+(1.96*`.se.fit`)) %>%
  rename(prob=`.fitted`)

probs_simple <- preds_simple %>%
  select(prob,lci,uci, depfreq_often, depfreq_monthly, HRSLEEP, chronic)
```

```{r, warning = FALSE, message = FALSE}
# code from Logistic Regression visualizationpractice activity 4/20/20
probs_simple <- probs_simple %>%
  filter(HRSLEEP %in% c(4, 5, 6, 7, 8, 9, 10)) %>%
  group_by(HRSLEEP, depfreq_often) %>%
  mutate(depfreq_often2 = ifelse(depfreq_often == 1, "Often", "Rarely")) %>% 
  slice(1)

p4 <- ggplot(probs_simple, aes(y = prob, x = HRSLEEP, color = as.factor(depfreq_often2))) +
      geom_pointrange(aes(ymin = lci, ymax = uci),
                      position = position_dodge(width = 3),
                      size = .75) +
        labs(
          title = "Probability of having Diabetes by Sleep and Depression",
          subtitle = "Model 4: Simple",
          y = "Probability of having Diabetes", 
          x = "Hours of Sleep per Night",
          color = "Depression Frequency") +
        theme_bw()

g4 <- as.grob(p4)
```

```{r}
arrangeGrob(g1, g2, ncol = 2)
```

